[ids]

# AT Translated Set 2 keyboard (/dev/input/event2)
k:0001:0001

[main]

# Oneshot
leftshift = oneshot(shift)
rightshift = oneshot(shift)

# Layers
capslock = overload(nav, esc)
apostrophe = overload(num, apostrophe)
backslash = overload(sym, backslash)

# For regular key presses and mapping, use us layout key locations e.g. on colemak-dh,
# use "f" for the letter t, since f is the key under the left index finger on a us layout

# home row mods
f = lettermod(shift, f, 150, 175)
d = lettermod(control, d, 150, 175)
s = lettermod(alt, s, 150, 175)
a = lettermod(meta, a, 150, 175)

j = lettermod(shift, j, 150, 175)
k = lettermod(control, k, 150, 175)
l = lettermod(alt, l, 150, 175)
; = lettermod(meta, ;, 150, 175)

[shift]

# Ensure capslock can active nav layer when holding shift
capslock = overload(nav, capslock)

[nav]

# Reset other keys
leftshift = layer(shift)
rightshift = layer(shift)
capslock = esc
backslash = backslash
f = layer(shift)
d = layer(control)
s = layer(alt)
a = layer(meta)

j = left
k = down
l = up
; = right

m = home
, = pagedown
. = pageup
/ = end

# Macros use reverse layout mapped keys, e.g. C-x for copy when using colemak-dh,
# since c is located where the x is on a us layout

# paste
u = C-v
# copy
i = C-x
# cut
o = C-z
# undo
p = C-102nd
# redo
y = S-C-102nd

# save and exit vim/helix
apostrophe = macro(esc P w q enter)

[num]

backspace = delete

# Reset other keys
rightshift = layer(shift)
backslash = backslash
j = layer(shift)
k = layer(control)
l = layer(alt)
; = layer(meta)

s = 1
d = 2
f = 3
z = 4
x = 5
c = 6
w = 7
e = 8
r = 9
space = 0

v = +
leftalt = -
leftmeta = equal
g = *
t = /
q = ^
102nd = .

a = !
leftshift = macro(->)
capslock = macro(=>)

[sym]

# Reset other keys
capslock = esc
leftshift = layer(shift)
rightshift = layer(shift)
apostrophe = apostrophe
j = layer(shift)
k = layer(control)
l = layer(alt)
; = layer(meta)

q = ~
w = {
e = }
r = $
# backslash
t = b
# colon
a = P
s = (
d = )
# semicolon
f = p
g = S-2
102nd = %
z = [
x = ]
c = &
# pipe
v = S-b

space = `
leftalt = _
