[ids]

# AT Translated Set 2 keyboard (/dev/input/event2)
k:0001:0001

[global]

# Cancel oneshot after timeout (in ms)
oneshot_timeout = 2000

[main]

# Layout functions:
#
# overload(<tap key>, <hold action>) is the basic "mod-tap" function
#
# oneshot(<layer>)
#   - Activate <layer> for value of global oneshot_timeout
#
# lettermod(<layer>, <key>, <idle timeout>, <hold timeout>) for home row mods
#   - If key is pressed after the last non-action key within <idle-timeout>, output key
#   - If key is pressed after the last non-action key past <idle-timeout>, but held for
#     less than <hold timeout>, output key
#   - Otherwise activate hold action

# Modified Colemak-DH layout
e = f
r = p
t = b
y = j
u = l
i = u
o = y
p = ;

# home row mods
a = lettermod(meta, a, 100, 175)
s = lettermod(alt, r, 100, 175)
d = lettermod(control, s, 100, 175)
f = lettermod(shift, t, 100, 175)
h = m
j = lettermod(shift, n, 100, 175)
k = lettermod(control, e, 100, 175)
l = lettermod(alt, i, 100, 175)
; = lettermod(meta, o, 100, 175)

# 102nd is backslash (\|) key on ISO layout
102nd = z
z = lettermod(altgr, x, 100, 175)
x = c
c = d
b = 102nd
n = k
m = h
. = lettermod(altgr, ., 100, 175)

# Oneshots
rightalt = overload(altgr, oneshot(shift))

# Layers
capslock = overload(nav, esc)
apostrophe = overload(num, apostrophe)

# backslash is #/~ on ISO layout
\ = overload(sym, #)

[shift]

# Ensure capslock can active nav layer when holding shift
capslock = overload(nav, capslock)

# backslash is #/~ on ISO layout
\ = ~

[meta]

# Toggle us qwerty layout using default GNOME meta+shift keyboard shortcut
space = toggle(qwerty)

[nav]

# Reset other keys
capslock = esc
backslash = backslash
f = layer(shift)
d = layer(control)
s = layer(alt)
a = layer(meta)

backspace = delete

j = left
k = down
l = up
; = right

m = home
, = pagedown
. = pageup
/ = end


# paste
u = C-v
# copy
i = C-c
# cut
o = C-x
# undo
p = C-z
# redo
y = S-C-z

# save and exit vim/helix
apostrophe = macro(esc P w q enter)

[num]

# Reset other keys
backslash = backslash
j = layer(shift)
k = layer(control)
l = layer(alt)
; = layer(meta)

s = 1
d = 2
f = 3
z = 4
x = 5
c = 6
w = 7
e = 8
r = 9
space = 0

v = +
leftalt = -
leftmeta = equal
g = *
t = /
q = ^
102nd = .

a = !
leftshift = macro(->)
capslock = macro(=>)

[sym]

# Reset other keys
capslock = esc
apostrophe = apostrophe
j = layer(shift)
k = layer(control)
l = layer(alt)
; = layer(meta)

q = ~
w = {
e = }
r = $
t = \
a = :
s = (
d = )
f = ;
g = @
102nd = %
z = [
x = ]
c = &
v = |

space = `
leftalt = _

[qwerty]

q = q
w = w
e = e
r = r
t = t
y = y
u = u
i = i
o = o
p = p

a = a
s = s
d = d
f = f
g = g
m = m
j = j
k = k
l = l
; = ;
' = '
\ = \

102nd = 102nd
z = z
x = x
c = c
v = v
b = b
n = n
m = m
, = ,
. = .
/ = /
